name: Deploy Docker Container

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted  # This requires a self-hosted runner on your deployment server
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Stop existing container
        run: |
          docker stop moojee-container || true
          docker rm moojee-container || true
        continue-on-error: true

      - name: Pull latest image
        run: docker pull utilitee/moojee-project:latest

      - name: Run container
        run: |
          docker run -d \
            --name moojee-container \
            --restart always \
            -p 2080:80 \
            utilitee/moojee-project:latest
