# .github/workflows/docker-build.yml
name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # or "master", depending on your default branch name
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/moojee-project:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/moojee-project:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
